<form method="post" action="/create">
    <h2>Création de compte</h2>
    <input type="hidden" name="form-name" value="create"/>
    <fieldset>
           <label for="firstname">Firstname :</label>
        <input type="text" name="firstname"/> 
    </fieldset>
    <fieldset>
        <label for="lastname">Lastname :</label>
        <input type="text" name="lastname"/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="text" name="email"/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Submit"/>
    </fieldset>
</form>